version: "3"
services:
    nginx:
        image: nginx:latest
        ports:
            - "8081:80"
        volumes:
            - .:/app
            - ./docker/nginx/:/etc/nginx/conf.d/
        depends_on:
            - php-fpm
        working_dir: /app
        networks:
            - internal
    php-fpm:
        user: ${HOST_USER}
        working_dir: /app
        build:
            context: ./docker/php-fpm
            dockerfile: Dockerfile
        volumes:
            - .:/app
            - ./docker/php-fpm/log/:/var/log/
            - /etc/group:/etc/group:ro
            - /etc/passwd:/etc/passwd:ro
        ports:
            - '9000:9000'
        networks:
            - internal
        environment:
            XDEBUG_CONFIG: "remote_enable=1"
            PHP_IDE_CONFIG: "serverName=SFCASTS"
            COMPOSER_AUTH: ${COMPOSER_AUTH}
            COMPOSER_MEMORY_LIMIT: ${COMPOSER_MEMORY_LIMIT}
    mysql:
        image: mysql:8.0
        environment:
            MYSQL_DATABASE: ${MYSQL_DATABASE}
            MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
            MYSQL_HOST: ${MYSQL_HOST}
        ports:
            - "8991:3306"
        volumes:
            - ./docker/mysql:/var/lib/mysql
        networks:
            - internal
        command:
            - "--default-authentication-plugin=mysql_native_password"
networks:
    internal:
        driver: bridge
        ipam:
            driver: default
            config:
                -   subnet: ${DOCKER_NETWORK_IP}